#!/bin/bash
export JAVA_HOME=/home/xuxiaorong/Programs/jdk5
export JDK_HOME=$JAVA_HOME
export JRE_HOME=$JAVA_HOME/jre
export ANT_HOME=/home/xuxiaorong/Programs/apache-ant-1.8.1
export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$ANT_HOME/bin:$PATH
export CLASSPATH=$JAVA_HOME/lib:$JRE_HOME/lib:$JAVA_HOME/lib/tools.jar

#test
