#!/bin/zsh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice


################  FCITX ################
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim

killall fcitx
fcitx &
########################################

#export GTK_IM_MODULE=ibus
#export XMODIFIERS="@im=ibus"
#export QT_IM_MODULE=ibus
# export QT_IM_MODULE=xim

#killall ibus
#killall ibus-daemon
#ibus-daemon -d -x

#######################################

# wice-client &

# set CapsLk as Ctrl, and Ctrl_L as Super_L
xmodmap ~/.Xmodmap 2>/dev/null

# External output may be "VGA" or "VGA-0" or "DVI-0" or "TMDS-1"
EXTERNAL_OUTPUT="VGA-0"
INTERNAL_OUTPUT="LVDS"
# EXTERNAL_LOCATION may be one of: left, right, above, or below
EXTERNAL_LOCATION="right"

case "$EXTERNAL_LOCATION" in
       left|LEFT)
               EXTERNAL_LOCATION="--left-of $INTERNAL_OUTPUT"
               ;;
       right|RIGHT)
               EXTERNAL_LOCATION="--right-of $INTERNAL_OUTPUT"
               ;;
       top|TOP|above|ABOVE)
               EXTERNAL_LOCATION="--above $INTERNAL_OUTPUT"
               ;;
       bottom|BOTTOM|below|BELOW)
               EXTERNAL_LOCATION="--below $INTERNAL_OUTPUT"
               ;;
       *)
               EXTERNAL_LOCATION="--left-of $INTERNAL_OUTPUT"
               ;;
esac

#xrandr |grep $EXTERNAL_OUTPUT | grep " connected "
#if [ $? -eq 0 ]; then
    #xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto $EXTERNAL_LOCATION
    #xrandr --output $INTERNAL_OUTPUT --primary --auto --output $EXTERNAL_OUTPUT --auto --right-of LVDS --pos 1280x0
    #xrandr --output $INTERNAL_OUTPUT --primary --auto --output $EXTERNAL_OUTPUT --auto --right-of $INTERNAL_OUTPUT
    # Alternative command in case of trouble:
    # (sleep 2; xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --auto $EXTERNAL_LOCATION) &
#else
    #xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --off
#fi

dropboxd &
exec awesome
